# Generated by Django 6.0.7 on 2026-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_adha_only',
            field=models.BooleanField(default=False),
        ),
    ]
