# Generated by Django 6.0.7 on 2026-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_category_is_adha_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
